configMapGenerator:
- files:
  - application.yml
  name: 82107454-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82107454
  newTag: "202408120727"
- name: cepgstapacr.azurecr.io/demo
  newTag: "202411110558"
