# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: workflow_dispatch

env:
  IMAGE_NAME: 82107454

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: 'Gen Version'
      id: gen-version
      run: |
        echo "::set-output name=VERSION::`date +%Y%m%d%H%M`"
        
    - name: 'ACR login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.BASEACR_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build & Tag Image'
      run: |
            docker pull cepgbaseacr.azurecr.io/troubleshooting
            docker tag cepgbaseacr.azurecr.io/troubleshooting:latest ${{ secrets.STAPACR_LOGIN_SERVER }}/troubleshooting:82107454

    - name: 'Push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.STAPACR_LOGIN_SERVER }}
        username: ${{ secrets.PRD_REGISTRY_USERNAME }}
        password: ${{ secrets.PRD_REGISTRY_PASSWORD }}
    
    - run: |
          docker push ${{ secrets.STAPACR_LOGIN_SERVER }}/troubleshooting:82107454

    - name: Update Kubernetes resources
      run: |
          cd manifests/overlays/prod
          kustomize edit set image ${{ secrets.STAPACR_LOGIN_SERVER }}/troubleshooting:82107454
          cat kustomization.yaml

    - name: Commit files
      run: |
          cd manifests
          git config --global user.email "sohwi20@gmail.com"
          git config --global user.name "so2"
          git commit -am "Update image tag"
          git push -u origin main
